"use client";
import { useEffect, useState } from "react";
import { useERP } from "../ERPContext";
import { money } from "../../lib/erp";
import { Button, Empty, Panel, Status, Table } from "../UI";
import InvoiceModal from "../InvoiceModal";
import { SaleForm } from "../forms/TransactionForms";
const download=(name,content)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const csv=rows=>{if(!rows.length)return"";const keys=Object.keys(rows[0]);return[keys.join(","),...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n")};

export default function LedgersScreen({initialPartyId="",clearInitial}){
 const {state}=useERP(); const [tab,setTab]=useState(initialPartyId?"Party ledger":"Overall ledger"),[partyId,setPartyId]=useState(initialPartyId||""),[nature,setNature]=useState("Customer"),[invoiceId,setInvoiceId]=useState(null),[editId,setEditId]=useState(null);
 useEffect(()=>{if(initialPartyId){setPartyId(initialPartyId);setTab("Party ledger");clearInitial?.()}},[initialPartyId]);
 const party=state.parties.find(p=>p.id===partyId),invoice=state.sales.find(s=>s.id===invoiceId),editable=state.sales.find(s=>s.id===editId);
 let balance=0; const baseRows=state.partyLedger.filter(r=>r.partyId===partyId).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>{balance+=(Number(r.debit||0)-Number(r.credit||0))*(nature==="Supplier"?-1:1);return{...r,balance}});
 const partyRows=baseRows.flatMap(row=>{const source=(nature==="Customer"?state.sales:state.purchases).find(x=>x.document===row.document),isInvoice=nature==="Customer"?Number(row.debit)>0:Number(row.credit)>0;if(!source||!isInvoice)return[{...row,itemName:"—",quantity:"—",unitPrice:null,lineTotal:null,source:null,received:nature==="Customer"?row.credit:row.debit}];return source.lines.map((line,index)=>({...row,id:`${row.id}-${index}`,date:index===0?row.date:"",document:index===0?row.document:"",itemName:state.items.find(i=>i.id===line.itemId)?.name||"—",quantity:line.quantity,unitPrice:Number(line.rate),lineTotal:Number(line.quantity)*Number(line.rate),received:0,balance:index===source.lines.length-1?row.balance:null,source,index}))});
 const journal=state.journal.flatMap(e=>e.lines.map((l,i)=>({id:`${e.id}-${i}`,date:e.date,document:e.document,description:e.description,party:state.parties.find(p=>p.id===e.partyId)?.name||"—",account:l.accountName,debit:l.debit||0,credit:l.credit||0}))),tabs=["Overall ledger","Party ledger","Account ledger","Invoices"];
 return <><div className="page-title"><div><p className="eyebrow">ACCOUNTING BOOKS</p><h1>Ledgers</h1><p>Complete journal, itemized party statements, account books and invoices.</p></div><Button variant="outline" onClick={()=>download("ledger.csv",csv(tab==="Party ledger"?partyRows:journal))}>Export current view</Button></div><div className="tabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==="Overall ledger"&&<Panel eyebrow="GENERAL JOURNAL" title="Overall ledger">{journal.length?<Table headers={["Date","Document","Description","Party","Account","Debit","Credit"]}>{journal.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.document}</b></td><td>{r.description}</td><td>{r.party}</td><td>{r.account}</td><td className="amount">{r.debit?money(r.debit):"—"}</td><td className="amount">{r.credit?money(r.credit):"—"}</td></tr>)}</Table>:<Empty title="Overall ledger is empty" text="Balanced entries appear when transactions are posted."/>}</Panel>}
 {tab==="Party ledger"&&<Panel eyebrow="CUSTOMER / SUPPLIER STATEMENT" title={party?.name||"Specific party ledger"} actions={<><select value={nature} onChange={e=>{setNature(e.target.value);setPartyId("")}}><option>Customer</option><option>Supplier</option></select><select value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">Select party</option>{state.parties.filter(p=>nature==="Customer"?["Customer","Both"].includes(p.type):["Supplier","Both"].includes(p.type)).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></>}>{partyRows.length?<><div className="statement-strip"><div><small>PARTY</small><b>{party?.name}</b></div><div><small>TYPE</small><b>{nature}</b></div><div><small>CLOSING BALANCE</small><b>{money(baseRows.at(-1)?.balance)}</b></div></div><Table headers={["Date","Invoice / document","Item name","Quantity","Price per unit","Product total",nature==="Customer"?"Received":"Sent","Running balance","Open"]}>{partyRows.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.document}</b></td><td>{r.itemName}</td><td className="amount">{r.quantity}</td><td className="amount">{r.unitPrice===null?"—":money(r.unitPrice)}</td><td className="amount">{r.lineTotal===null?"—":<b>{money(r.lineTotal)}</b>}</td><td className="amount">{r.received?money(r.received):"—"}</td><td className="amount">{r.balance===null?"":<b>{money(r.balance)}</b>}</td><td>{r.source&&nature==="Customer"&&r.index===0?<button className="text-link" onClick={()=>setInvoiceId(r.source.id)}>Invoice</button>:"—"}</td></tr>)}</Table></>:<Empty title="No party ledger entries" text="Select a party to view invoices and payments."/>}</Panel>}
 {tab==="Account ledger"&&<AccountLedger journal={journal}/>} {tab==="Invoices"&&<InvoiceRegister state={state} open={setInvoiceId}/>} {invoice&&<InvoiceModal sale={invoice} state={state} close={()=>setInvoiceId(null)} onEdit={()=>{setInvoiceId(null);setEditId(invoice.id)}}/>} {editable&&<SaleForm sale={editable} close={()=>setEditId(null)}/>}</>;
}
function AccountLedger({journal}){const names=[...new Set(journal.map(r=>r.account))],[name,setName]=useState(names[0]||"");let running=0;const rows=journal.filter(r=>r.account===name).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({...r,balance:running+=Number(r.debit)-Number(r.credit)}));return <Panel eyebrow="CHART OF ACCOUNTS" title={name||"Account ledger"} actions={<select value={name} onChange={e=>setName(e.target.value)}><option value="">Select account</option>{names.map(n=><option key={n}>{n}</option>)}</select>}>{rows.length?<Table headers={["Date","Document","Description","Debit","Credit","Running balance"]}>{rows.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.document}</b></td><td>{r.description}</td><td className="amount">{r.debit?money(r.debit):"—"}</td><td className="amount">{r.credit?money(r.credit):"—"}</td><td className="amount"><b>{money(r.balance)}</b></td></tr>)}</Table>:<Empty title="No account entries" text="Choose an account with posted transactions."/>}</Panel>}
function InvoiceRegister({state,open}){return <Panel eyebrow="SOURCE DOCUMENTS" title="Sales invoices">{state.sales.length?<Table headers={["Invoice","Date","Customer","Items","Quantity","Total","Received","Balance","Status","Open"]}>{state.sales.map(s=><tr key={s.id}><td><b>{s.document}</b></td><td>{s.date}</td><td>{state.parties.find(p=>p.id===s.partyId)?.name}</td><td>{s.lines.map(l=>state.items.find(i=>i.id===l.itemId)?.name).join(", ")}</td><td className="amount">{s.lines.reduce((n,l)=>n+Number(l.quantity),0)}</td><td className="amount">{money(s.total)}</td><td className="amount">{money(s.paid)}</td><td className="amount">{money(s.total-s.paid)}</td><td><Status>{s.status}</Status></td><td><button className="text-link" onClick={()=>open(s.id)}>View / print</button></td></tr>)}</Table>:<Empty title="No invoices" text="Sales invoices appear here after posting."/>}</Panel>}
