"use client";

import { useState } from "react";
import { useERP } from "../ERPContext";
import { deleteSale, money, partyBalance, stockFor, updatePendingOrderStatus } from "../../lib/erp";
import { dateNow } from "../../lib/schema";
import { Button, Empty, Panel, SearchableSelect, Status, Table } from "../UI";
import InvoiceModal from "../InvoiceModal";
import { SaleForm } from "../forms/TransactionForms";

export function DashboardScreen({ open, navigate }) {
  const { state } = useERP();
  const stockValue = state.items.reduce((sum, item) => sum + stockFor(state, item.id) * Number(item.cost || 0), 0);
  const receivable = state.parties.filter(party => ["Customer", "Both"].includes(party.type)).reduce((sum, party) => sum + Math.max(0, partyBalance(state, party.id)), 0);
  const payable = state.parties.filter(party => ["Supplier", "Both"].includes(party.type)).reduce((sum, party) => sum + Math.max(0, partyBalance(state, party.id)), 0);
  const low = state.items.filter(item => stockFor(state, item.id) <= Number(item.minStock)), configured = state.items.length && state.parties.length && state.accounts.length;
  const chequeReminders = state.payments.filter(payment => payment.paymentMethod === "Cheque" && payment.chequeDate && payment.chequeDate <= dateNow() && payment.chequeStatus !== "Cleared").sort((a, b) => a.chequeDate.localeCompare(b.chequeDate));
  return <><div className="hero"><div><p className="eyebrow">APEX ENGINEERING / MANUFACTURING ERP</p><h1>{configured ? "Factory position at a glance." : "Build your factory system."}</h1><p>{configured ? "Every posted movement is reflected in stock, accounts and party balances." : "Start with masters. No dummy transactions have been added."}</p></div><Button onClick={() => open("production")}>+ Produce</Button></div>{chequeReminders.length > 0 && <Panel eyebrow="DUE TODAY / OVERDUE" title="Cheque reminders" description="These posted cheques have reached their cheque date."><div className="alert-list">{chequeReminders.map(payment => <button key={payment.id} onClick={() => navigate("Cash & bank")}><span><b>{payment.chequeNumber || payment.document} · {state.parties.find(party => party.id === payment.partyId)?.name}</b><small>{payment.chequeDate === dateNow() ? "Due today" : `Overdue since ${payment.chequeDate}`} · {payment.direction} · {money(payment.amount)}</small></span><i>›</i></button>)}</div></Panel>}{!configured && <div className="setup-roadmap">{[["01", "Add items", "Materials and products", "item"], ["02", "Add customer", "Customer accounts", "customer"], ["03", "Add supplier", "Supplier accounts", "supplier"], ["04", "Add cash/bank", "Payment accounts", "account"], ["05", "Create BOM", "Recipe and costs", "bom"]].map(row => <div key={row[0]}><span>{row[0]}</span><section><b>{row[1]}</b><small>{row[2]}</small></section><button onClick={() => open(row[3])}>Set up</button></div>)}</div>}<div className="kpi-grid">{[["Stock value", stockValue, "Items & stock"], ["Receivables", receivable, "Ledger"], ["Payables", payable, "Ledger"], ["Pending orders", state.pendingOrders.length, "Pending orders"], ["Low-stock items", low.length, "Items & stock"]].map(([label, value, page]) => <button key={label} onClick={() => navigate(page)}><span>{label}</span><strong>{["Pending orders", "Low-stock items"].includes(label) ? value : money(value)}</strong><small>Open details →</small></button>)}</div><div className="two-column"><Panel eyebrow="RECENT ACTIVITY" title="Audit trail">{state.audit.length ? <div className="activity-list">{state.audit.slice(0, 8).map(entry => <div key={entry.id}><span>{entry.action}</span><small>{new Date(entry.at).toLocaleString()} · {entry.user}</small></div>)}</div> : <Empty title="No activity yet" text="Actions appear here as you operate the ERP." />}</Panel><Panel eyebrow="STOCK ALERTS" title="Reorder attention">{low.length ? <div className="alert-list">{low.slice(0, 8).map(item => <button onClick={() => navigate("Items & stock")} key={item.id}><span><b>{item.name}</b><small>{stockFor(state, item.id)} {item.unit} available · minimum {item.minStock}</small></span><i>›</i></button>)}</div> : <Empty title="No low-stock item" text="Low-stock warnings appear after minimum levels are configured." />}</Panel></div></>;
}

export function ProductionScreen({ open }) {
  const { state } = useERP();
  return <><div className="page-title"><div><p className="eyebrow">MANUFACTURING CONTROL</p><h1>Production management</h1><p>Consume BOM materials and receive finished goods automatically.</p></div><Button onClick={() => open("production")}>+ New production</Button></div><Panel eyebrow="POSTED ORDERS" title="Production history">{state.productions.length ? <Table headers={["Production", "Date", "Product", "Quantity", "Material", "Conversion", "Total cost", "Unit cost", "Status"]}>{state.productions.map(production => <tr key={production.id}><td><b>{production.document}</b></td><td>{production.date}</td><td>{state.items.find(item => item.id === production.bomSnapshot.productId)?.name}</td><td className="amount">{production.quantity}</td><td className="amount">{money(production.materialCost)}</td><td className="amount">{money(production.conversionCost)}</td><td className="amount">{money(production.totalCost)}</td><td className="amount">{money(production.unitCost)}</td><td><Status>{production.status}</Status></td></tr>)}</Table> : <Empty title="No production posted" text="Create a BOM, then post production to update stock and costs." action={<Button onClick={() => open("production")}>Post production</Button>} />}</Panel></>;
}

export function PurchasesScreen({ open }) {
  const { state } = useERP();
  return <><div className="page-title"><div><p className="eyebrow">PROCUREMENT</p><h1>Purchase management</h1><p>Receive materials and create vendor payables in one posting.</p></div><Button onClick={() => open("purchase")}>+ New purchase</Button></div><Panel eyebrow="PURCHASE REGISTER" title="Vendor invoices">{state.purchases.length ? <Table headers={["Purchase", "Supplier invoice", "Vendor", "Date", "Due", "Total", "Sent", "Balance", "Status"]}>{state.purchases.map(purchase => <tr key={purchase.id}><td><b>{purchase.document}</b></td><td>{purchase.supplierInvoice}</td><td>{state.parties.find(party => party.id === purchase.partyId)?.name}</td><td>{purchase.date}</td><td>{purchase.dueDate || "—"}</td><td className="amount">{money(purchase.total)}</td><td className="amount">{money(purchase.paid)}</td><td className="amount">{money(purchase.total - purchase.paid)}</td><td><Status>{purchase.status}</Status></td></tr>)}</Table> : <Empty title="No purchases" text="Add a supplier and raw material before posting a purchase." action={<Button onClick={() => open("purchase")}>Post purchase</Button>} />}</Panel></>;
}

export function SalesScreen({ open }) {
  const { state, mutate } = useERP();
  const [view, setView] = useState(null), [edit, setEdit] = useState(null);
  const sale = state.sales.find(row => row.id === view), editable = state.sales.find(row => row.id === edit);
  const remove = row => { if (window.confirm(`Delete ${row.document}? Stock, customer ledger and accounting entries will be reversed.`)) { mutate(current => deleteSale(current, row.id), "sales"); setView(null); setEdit(null); } };
  return <><div className="page-title"><div><p className="eyebrow">SALES & RECEIVABLES</p><h1>Invoices</h1><p>Issue goods and update the customer ledger automatically.</p></div><Button onClick={() => open("sale")}>+ New invoice</Button></div><Panel eyebrow="SALES REGISTER" title="Customer invoices">{state.sales.length ? <Table headers={["Invoice", "Customer", "Date", "Due", "Total", "Received", "Balance", "Status", "Actions"]}>{state.sales.map(row => <tr key={row.id}><td><b>{row.document}</b></td><td>{state.parties.find(party => party.id === row.partyId)?.name}</td><td>{row.date}</td><td>{row.dueDate || "—"}</td><td className="amount">{money(row.total)}</td><td className="amount">{money(row.paid)}</td><td className="amount">{money(row.total - row.paid)}</td><td><Status>{row.status}</Status></td><td><div className="table-actions"><button className="text-link" onClick={() => setView(row.id)}>View / print</button><button className="text-link" onClick={() => setEdit(row.id)}>Edit</button><button className="text-link" onClick={() => remove(row)}>Delete</button></div></td></tr>)}</Table> : <Empty title="No sales invoices" text="Create an invoice after adding a customer and stock." action={<Button onClick={() => open("sale")}>Create invoice</Button>} />}</Panel>{sale && <InvoiceModal sale={sale} state={state} close={() => setView(null)} onEdit={() => { setView(null); setEdit(sale.id); }} onDelete={() => remove(sale)} />}{editable && <SaleForm sale={editable} close={() => setEdit(null)} />}</>;
}

export function PendingOrdersScreen({ open }) {
  const { state, mutate } = useERP();
  const setStatus = (id, status) => mutate(current => updatePendingOrderStatus(current, id, status), "sales");
  return <><div className="page-title"><div><p className="eyebrow">CUSTOMER DEMAND PIPELINE</p><h1>Pending orders</h1><p>Track requested products, quantities, agreed unit prices and required dates before invoicing.</p></div><Button onClick={() => open("pendingOrder")}>+ Add pending order</Button></div><Panel eyebrow="ORDER REGISTER" title="Customer requirements">{state.pendingOrders.length ? <Table headers={["Order", "Customer / company", "Pending date", "Required date", "Item", "Required quantity", "Price per piece", "Line total", "Status", "Update"]}>{state.pendingOrders.flatMap(order => order.lines.map((line, index) => <tr key={`${order.id}-${index}`}><td>{index === 0 ? <b>{order.document}</b> : ""}</td><td>{index === 0 ? state.parties.find(party => party.id === order.partyId)?.name : ""}</td><td>{index === 0 ? order.pendingDate : ""}</td><td>{index === 0 ? order.requiredDate || "—" : ""}</td><td>{state.items.find(item => item.id === line.itemId)?.name}</td><td className="amount">{line.quantity}</td><td className="amount">{money(line.rate)}</td><td className="amount"><b>{money(Number(line.quantity) * Number(line.rate))}</b></td><td>{index === 0 ? <Status>{order.status}</Status> : ""}</td><td>{index === 0 ? <SearchableSelect value={order.status} onChange={event => setStatus(order.id, event.target.value)}><option>Pending</option><option>Partially Fulfilled</option><option>Fulfilled</option><option>Cancelled</option></SearchableSelect> : ""}</td></tr>))}</Table> : <Empty title="No pending orders" text="Add a customer's requested products, quantity, unit price and required date." action={<Button onClick={() => open("pendingOrder")}>Add pending order</Button>} />}</Panel></>;
}
