"use client";
import { useEffect, useState } from "react";
import { useERP } from "./ERPContext";
import LoginPanel from "./LoginPanel";
import { Button } from "./UI";
import { AccountForm, ItemForm, PartyForm, RackForm, StockActionForm } from "./forms/CommonForms";
import { BOMForm, ExpenseForm, PaymentForm, PendingOrderForm, ProductionForm, PurchaseForm, SaleForm, UserForm } from "./forms/TransactionForms";
import { BOMScreen, ItemsStockScreen, PartiesScreen, RawMaterialsScreen } from "./screens/Masters";
import { DashboardScreen, PendingOrdersScreen, ProductionScreen, PurchasesScreen, SalesScreen } from "./screens/Operations";
import { CashBankScreen, ExpensesScreen, ReportsScreen, SettingsScreen } from "./screens/Finance";
import LedgersScreen from "./screens/Ledgers";

const pages=[["Dashboard","D","view"],["Items & stock","I","stock"],["Raw materials","W","stock"],["Pending orders","O","sales"],["Parties","P","parties"],["BOM","B","bom"],["Production","M","production"],["Purchases","R","purchases"],["Sales & invoices","S","sales"],["Cash & bank","C","accounts"],["Ledgers","L","ledgers"],["Expenses","E","expenses"],["Reports","T","reports"],["Settings & backup","G","all"]];

export default function AppShell(){
 const {ready,user,logout,can,saving,syncError}=useERP(); const [page,setPage]=useState("Dashboard"),[modal,setModal]=useState(""),[theme,setTheme]=useState("light"),[ledgerParty,setLedgerParty]=useState("");
 useEffect(()=>{const saved=localStorage.getItem("apex-erp-theme");if(saved)setTheme(saved)},[]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("apex-erp-theme",theme)},[theme]);
 if(!ready)return <div className="loading">Loading Apex Engineering ERP…</div>; if(!user)return <LoginPanel/>;
 const navigate=next=>setPage(next),goLedger=id=>{setLedgerParty(id);setPage("Ledgers")},visible=pages.filter(([, ,permission])=>can(permission));
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span>AE</span><div><strong>APEX</strong><small>ENGINEERING ERP</small></div></div><nav>{visible.map(([name,icon])=><button key={name} className={page===name?"active":""} onClick={()=>navigate(name)}><i>{icon}</i><span>{name}</span></button>)}</nav><footer><button onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?"Switch to dark":"Switch to light"}</button><div><span>{user.name?.slice(0,2).toUpperCase()}</span><section><b>{user.name}</b><small>{user.role} · <button className="logout-link" onClick={logout}>Sign out</button></small></section></div></footer></aside><main><header className="topbar"><div><p>APEX ENGINEERING · {saving?"SAVING…":syncError?"SYNC ATTENTION":"SYNCED"}</p><b>{page}</b></div><div>{can("accounts")&&<Button variant="outline" onClick={()=>setModal("payment")}>Receipt / payment</Button>}{can("sales")&&<Button onClick={()=>setModal("sale")}>+ Sales invoice</Button>}</div></header>{syncError&&<div className="sync-error">{syncError}</div>}<section className="content">{page==="Dashboard"&&<DashboardScreen open={setModal} navigate={navigate}/>} {page==="Items & stock"&&<ItemsStockScreen open={setModal}/>} {page==="Raw materials"&&<RawMaterialsScreen open={setModal}/>} {page==="Pending orders"&&<PendingOrdersScreen open={setModal}/>} {page==="Parties"&&<PartiesScreen open={setModal} goLedger={goLedger}/>} {page==="BOM"&&<BOMScreen open={setModal}/>} {page==="Production"&&<ProductionScreen open={setModal}/>} {page==="Purchases"&&<PurchasesScreen open={setModal}/>} {page==="Sales & invoices"&&<SalesScreen open={setModal}/>} {page==="Cash & bank"&&<CashBankScreen open={setModal}/>} {page==="Ledgers"&&<LedgersScreen initialPartyId={ledgerParty} clearInitial={()=>setLedgerParty("")}/>} {page==="Expenses"&&<ExpensesScreen open={setModal}/>} {page==="Reports"&&<ReportsScreen/>} {page==="Settings & backup"&&<SettingsScreen open={setModal}/>}</section></main><Modals modal={modal} close={()=>setModal("")}/></div>;
}
function Modals({modal,close}){return <>{modal==="item"&&<ItemForm close={close}/>} {modal==="rawItem"&&<ItemForm close={close} defaultType="Raw Material"/>} {modal==="party"&&<PartyForm close={close}/>} {modal==="rack"&&<RackForm close={close}/>} {modal==="account"&&<AccountForm close={close}/>} {modal==="adjustment"&&<StockActionForm close={close}/>} {modal==="transfer"&&<StockActionForm close={close} mode="transfer"/>} {modal==="bom"&&<BOMForm close={close}/>} {modal==="production"&&<ProductionForm close={close}/>} {modal==="purchase"&&<PurchaseForm close={close}/>} {modal==="sale"&&<SaleForm close={close}/>} {modal==="pendingOrder"&&<PendingOrderForm close={close}/>} {modal==="payment"&&<PaymentForm close={close}/>} {modal==="expense"&&<ExpenseForm close={close}/>} {modal==="user"&&<UserForm close={close}/>}</>}
