"use client";

import { useEffect, useMemo, useState } from "react";
import { useERP } from "../ERPContext";
import { addBOM, addPendingOrder, money, postBankTransfer, postExpense, postPayment, postProduction, postPurchase, postSale, postServicePurchase, recordAudit, stockFor, updateBOM, updatePayment, updatePendingOrder, updatePurchase, updateSale, updateServicePurchase } from "../../lib/erp";
import { dateNow, id } from "../../lib/schema";
import { Button, ErrorText, Field, FormActions, Modal, SearchableSelect } from "../UI";

const emptyLine = () => ({ itemId: "", rackId: "", quantity: 1, rate: 0, labourCost: 0, laserMarkingCost: 0, labourCharge: 0, laserCharge: 0, labourSupplierId: "" });

function LinesEditor({ lines, setLines, items, racks, sale = false }) {
  const { state } = useERP();
  if (sale) items = state.items.filter(item => ["Finished Good", "Raw Material"].includes(item.type));
  const itemLabel = item => sale ? `${item.type === "Raw Material" ? "RAW" : "FG"} — ${item.name}` : `${item.sku} — ${item.name}`;
  const update = (index, key, value) => setLines(lines.map((line, i) => {
    if (i !== index) return line;
    const item = key === "itemId" ? items.find(x => x.id === value) : null;
    const isRawMaterial = sale && item?.type === "Raw Material";
    return { ...line, [key]: value, ...(item ? { rate: item[sale ? "saleRate" : "cost"] || 0, ...(sale ? { labourCost: isRawMaterial ? 0 : Number(item.labourCost || 0), laserMarkingCost: isRawMaterial ? 0 : Number(item.laserMarkingCost || 0), labourCharge: isRawMaterial ? Number(item.defaultLabourCharge || 0) : 0, laserCharge: 0, labourSupplierId: item.labourSupplierId || "", itemNameSnapshot: item.name } : {}) } : {}) };
  }));
  return <div className="line-editor"><div className={`line-grid line-head ${sale ? "sale-line-grid" : ""}`}><span>Item</span><span>Rack</span><span>Quantity</span><span>{sale ? "Sale rate" : "Purchase rate"}</span>{sale&&<><span>Labour charges</span><span>Laser marking</span></>}<span>{sale ? "Sale amount" : "Purchase amount"}</span><span /></div>{lines.map((line, index) => {const selectedItem=state.items.find(item=>item.id===line.itemId),isRawMaterial=sale&&selectedItem?.type==="Raw Material";return <div className={`line-grid ${sale ? "sale-line-grid" : ""}`} key={index}>
    <label className="line-field item-line-field"><span>Item</span><SearchableSelect value={line.itemId} onChange={e => update(index, "itemId", e.target.value)} required searchPlaceholder="Search items…"><option value="">Select item</option>{items.map(i => <option key={i.id} value={i.id}>{itemLabel(i)}</option>)}</SearchableSelect></label>
    <label className="line-field rack-line-field"><span>Rack</span><SearchableSelect value={line.rackId} onChange={e => update(index, "rackId", e.target.value)} searchPlaceholder="Search racks…"><option value="">No rack</option>{racks.map(r => <option key={r.id} value={r.id}>{r.code}</option>)}</SearchableSelect></label>
    <label className="line-field"><span>Quantity</span><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e => update(index, "quantity", e.target.value)} required /></label>
    <label className="line-field"><span>{sale ? "Sale rate" : "Purchase rate"}</span><input type="number" min="0" step="0.01" value={line.rate} onChange={e => update(index, "rate", e.target.value)} required /></label>
    {sale&&(isRawMaterial?<><label className="line-field"><span>Overall labour charges</span><input type="number" min="0" step="0.01" value={line.labourCharge||0} onChange={e=>update(index,"labourCharge",e.target.value)}/></label><label className="line-field"><span>Overall laser charges</span><input type="number" min="0" step="0.01" value={line.laserCharge||0} onChange={e=>update(index,"laserCharge",e.target.value)}/></label></>:<><label className="line-field"><span>Labour / unit</span><input type="number" min="0" step="0.01" value={line.labourCost||0} onChange={e => update(index, "labourCost", e.target.value)} /></label><label className="line-field"><span>Laser / unit</span><input type="number" min="0" step="0.01" value={line.laserMarkingCost||0} onChange={e => update(index, "laserMarkingCost", e.target.value)} /></label></>)}
    <div className="line-total"><span>{sale ? "Sale amount" : "Purchase amount"}</span><b>{money(Number(line.quantity) * Number(line.rate))}</b></div>
    <button type="button" aria-label="Remove line" onClick={() => lines.length > 1 && setLines(lines.filter((_, i) => i !== index))}>×</button>
   </div>})}<button className="add-row" type="button" onClick={() => setLines([...lines, emptyLine()])}>+ Add another line</button></div>;
}

export function PurchaseForm({ close, purchase = null }) {
  const { state, mutate } = useERP();
  const [lines, setLines] = useState(purchase?.lines?.map(line => ({ ...line })) || [emptyLine()]);
  const [discount, setDiscount] = useState(purchase?.discount || 0);
  const [charges, setCharges] = useState(purchase?.charges || 0);
  const [paid, setPaid] = useState(purchase?.paid || 0);
  const [error, setError] = useState("");
  const total = lines.reduce((s, l) => s + Number(l.quantity) * Number(l.rate), 0) - Number(discount) + Number(charges);
  const submit = (e) => { e.preventDefault(); try { const f = Object.fromEntries(new FormData(e.currentTarget)); mutate(s => purchase ? updatePurchase(s, purchase.id, { ...f, lines, discount, charges, paid }) : postPurchase(s, { ...f, lines, discount, charges, paid }), "purchases"); close(); } catch (err) { setError(err.message); } };
  return <Modal title={purchase ? `Edit ${purchase.document}` : "Post purchase invoice"} eyebrow="STOCK IN + VENDOR PAYABLE" close={close} wide><form onSubmit={submit}><div className="form-grid three"><Field label="Supplier"><SearchableSelect name="partyId" defaultValue={purchase?.partyId || ""} required searchPlaceholder="Search suppliers…"><option value="">Select supplier</option>{state.parties.filter(p => ["Supplier", "Both"].includes(p.type)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</SearchableSelect></Field><Field label="Purchase date"><input name="date" type="date" defaultValue={purchase?.date || dateNow()} required /></Field><Field label="Supplier invoice"><input name="supplierInvoice" defaultValue={purchase?.supplierInvoice || ""} required /></Field><Field label="Due date"><input name="dueDate" type="date" defaultValue={purchase?.dueDate || ""} /></Field><Field label="Paid now"><input value={paid} onChange={e => setPaid(e.target.value)} type="number" min="0" max={total} step="0.01" /></Field><Field label="Paid from"><SearchableSelect name="accountId" defaultValue={purchase?.accountId || ""} searchPlaceholder="Search accounts…"><option value="">Credit only</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></Field></div><LinesEditor lines={lines} setLines={setLines} items={state.items.filter(i => i.type !== "Finished Good")} racks={state.racks} /><div className="transaction-foot"><div className="form-grid two"><Field label="Discount"><input value={discount} onChange={e => setDiscount(e.target.value)} type="number" min="0" /></Field><Field label="Freight / charges"><input value={charges} onChange={e => setCharges(e.target.value)} type="number" min="0" /></Field></div><div className="document-total"><span>Purchase total</span><strong>{money(total)}</strong><small>Remaining payable: {money(total - Number(paid))}</small></div></div>{purchase && <p className="form-note">Saving reverses this supplier invoice's previous stock, ledger and journal postings, then reposts the corrected values under the same purchase number.</p>}<ErrorText>{error}</ErrorText><FormActions close={close} submit={purchase ? "Save supplier invoice changes" : "Post purchase"} /></form></Modal>;
}

const emptyServiceLine = () => ({ service: "", description: "", quantity: 1, rate: 0 });

export function ServicePurchaseForm({ close, servicePurchase = null }) {
  const { state, mutate } = useERP();
  const [lines, setLines] = useState(servicePurchase?.lines?.map(line => ({ ...line })) || [emptyServiceLine()]), [paid, setPaid] = useState(servicePurchase?.paid || 0), [error, setError] = useState("");
  const updateLine = (index, key, value) => setLines(lines.map((line, position) => position === index ? { ...line, [key]: value } : line));
  const total = lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.rate), 0);
  const submit = event => { event.preventDefault(); try { const values = { ...Object.fromEntries(new FormData(event.currentTarget)), lines, paid }; mutate(current => servicePurchase ? updateServicePurchase(current, servicePurchase.id, values) : postServicePurchase(current, values), "purchases"); close(); } catch (reason) { setError(reason.message); } };
  return <Modal title={servicePurchase ? `Edit ${servicePurchase.document}` : "Post outside-service bill"} eyebrow="SERVICE COST + VENDOR PAYABLE / NO STOCK" close={close} wide><form onSubmit={submit}>
    <div className="form-grid three">
      <Field label="Service supplier"><SearchableSelect name="partyId" defaultValue={servicePurchase?.partyId || ""} required searchPlaceholder="Search service suppliers…"><option value="">Select supplier</option>{state.parties.filter(party => ["Supplier", "Both"].includes(party.type)).map(party => <option key={party.id} value={party.id}>{party.name}</option>)}</SearchableSelect></Field>
      <Field label="Bill date"><input name="date" type="date" defaultValue={servicePurchase?.date || dateNow()} required /></Field>
      <Field label="Supplier bill / reference"><input name="supplierInvoice" defaultValue={servicePurchase?.supplierInvoice || ""} /></Field>
      <Field label="Due date"><input name="dueDate" type="date" defaultValue={servicePurchase?.dueDate || ""} /></Field>
      <Field label="Paid now"><input type="number" min="0" max={total} step="0.01" value={paid} onChange={event => setPaid(event.target.value)} /></Field>
      <Field label="Paid from"><SearchableSelect name="accountId" defaultValue={servicePurchase?.accountId || ""} searchPlaceholder="Search accounts…"><option value="">Credit only</option>{state.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</SearchableSelect></Field>
    </div>
    <datalist id="outside-service-types"><option>Tempering</option><option>Coloring</option><option>Threading</option><option>Laser marking</option><option>Heat treatment</option><option>Plating</option><option>Grinding</option><option>Machining</option><option>Transport</option></datalist>
    <div className="line-editor"><div className="service-line service-head"><span>Service</span><span>Details</span><span>Quantity</span><span>Rate</span><span>Total</span><span /></div>{lines.map((line, index) => <div className="service-line" key={index}><input list="outside-service-types" placeholder="Temper, color, threading…" value={line.service} onChange={event => updateLine(index, "service", event.target.value)} required /><input placeholder="Job / product detail" value={line.description} onChange={event => updateLine(index, "description", event.target.value)} /><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={event => updateLine(index, "quantity", event.target.value)} required /><input type="number" min="0" step="0.01" value={line.rate} onChange={event => updateLine(index, "rate", event.target.value)} required /><b>{money(Number(line.quantity) * Number(line.rate))}</b><button type="button" onClick={() => lines.length > 1 && setLines(lines.filter((_, position) => position !== index))}>×</button></div>)}<button className="add-row" type="button" onClick={() => setLines([...lines, emptyServiceLine()])}>+ Add service line</button></div>
    <div className="document-total service-total"><span>Service bill total</span><strong>{money(total)}</strong><small>Remaining payable: {money(total - Number(paid))}</small></div>
    <p className="form-note">This bill creates a supplier payable and service expense only. It never receives or changes inventory stock.</p><ErrorText>{error}</ErrorText><FormActions close={close} submit={servicePurchase ? "Save service bill changes" : "Post service bill"} />
  </form></Modal>;
}

export function SaleForm({ close, sale = null }) {
  const { state, mutate } = useERP();
  const [lines, setLines] = useState(sale?.lines?.map(line => { const item = state.items.find(row => row.id === line.itemId); return item?.type === "Raw Material" ? { ...line, labourCharge: Number(line.labourCharge ?? (Number(line.quantity) * Number(line.labourCost || 0))), laserCharge: Number(line.laserCharge ?? (Number(line.quantity) * Number(line.laserMarkingCost || 0))), labourCost: 0, laserMarkingCost: 0 } : { ...line, labourCharge: 0, laserCharge: 0 }; }) || [emptyLine()]);
  const [discount, setDiscount] = useState(sale?.discount || 0), [tax, setTax] = useState(sale?.tax || 0), [charges, setCharges] = useState(sale?.charges || 0), [paid, setPaid] = useState(sale?.paid || 0), [error, setError] = useState("");
  const subtotal = lines.reduce((s, l) => s + Number(l.quantity) * Number(l.rate), 0);
  const total = subtotal - Number(discount) + Number(tax) + Number(charges);
  const labourTotal = lines.reduce((sum, line) => sum + Number(line.labourCharge || 0) + Number(line.quantity) * Number(line.labourCost || 0), 0), laserTotal = lines.reduce((sum, line) => sum + Number(line.laserCharge || 0) + Number(line.quantity) * Number(line.laserMarkingCost || 0), 0);
  const submit = (e) => { e.preventDefault(); try { const f = Object.fromEntries(new FormData(e.currentTarget)); mutate(s => sale ? updateSale(s, sale.id, { ...f, lines, discount, tax, charges, paid }) : postSale(s, { ...f, lines, discount, tax, charges, paid }), "sales"); close(); } catch (err) { setError(err.message); } };
  return <Modal title={sale ? `Edit ${sale.document}` : "Post sales invoice"} eyebrow="STOCK OUT + CUSTOMER RECEIVABLE" close={close} wide><form onSubmit={submit}><div className="form-grid three"><Field label="Customer"><SearchableSelect name="partyId" defaultValue={sale?.partyId || ""} required searchPlaceholder="Search customers…"><option value="">Select customer</option>{state.parties.filter(p => ["Customer", "Both"].includes(p.type)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</SearchableSelect></Field><Field label="Invoice date"><input name="date" type="date" defaultValue={sale?.date || dateNow()} required /></Field><Field label="Due date"><input name="dueDate" type="date" defaultValue={sale?.dueDate || ""} /></Field><Field label="Received now"><input value={paid} onChange={e => setPaid(e.target.value)} type="number" min="0" max={total} step="0.01" /></Field><Field label="Received in"><SearchableSelect name="accountId" defaultValue={sale?.accountId || ""} searchPlaceholder="Search accounts…"><option value="">Credit only</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></Field><Field label="Customer reference"><input name="customerReference" defaultValue={sale?.customerReference || ""} /></Field></div><LinesEditor lines={lines} setLines={setLines} items={state.items.filter(i => i.type === "Finished Good")} racks={state.racks} sale /><div className="transaction-foot"><div className="form-grid three"><Field label="Discount"><input value={discount} onChange={e => setDiscount(e.target.value)} type="number" min="0" /></Field><Field label="Tax"><input value={tax} onChange={e => setTax(e.target.value)} type="number" min="0" /></Field><Field label="Other charges"><input value={charges} onChange={e => setCharges(e.target.value)} type="number" min="0" /></Field></div><div className="document-total"><span>Invoice total</span><strong>{money(total)}</strong><small>Remaining receivable: {money(total - Number(paid))}</small><small>Labour payable: {money(labourTotal)}</small><small>Laser marking payable: {money(laserTotal)}</small></div></div><p className="form-note">Finished products use labour and laser cost per unit. Raw materials show editable overall labour and laser charges; neither amount is multiplied by quantity. The supplier is taken automatically from the Raw Material master and both costs post to that supplier's ledger.</p><ErrorText>{error}</ErrorText><FormActions close={close} submit={sale ? "Save invoice changes" : "Post invoice"} /></form></Modal>;
}

export function PendingOrderForm({ close, order = null }) {
  const { state, mutate } = useERP(); const [lines, setLines] = useState(order?.lines?.map(line=>({...line}))||[{ itemId:"", quantity:1, rate:0 }]), [error,setError]=useState("");
  const update=(i,key,value)=>setLines(lines.map((l,n)=>n===i?{...l,[key]:value,...(key==="itemId"?{rate:state.items.find(x=>x.id===value)?.saleRate||0}:{})}:l));
  const submit=e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.currentTarget));mutate(s=>order?updatePendingOrder(s,order.id,{...f,lines}):addPendingOrder(s,{...f,lines}),"sales");close()}catch(err){setError(err.message)}};
  return <Modal title={order?`Edit ${order.document}`:"Add pending customer order"} eyebrow="ORDER PIPELINE" close={close} wide><form onSubmit={submit}><div className="form-grid three"><Field label="Customer / company"><SearchableSelect name="partyId" defaultValue={order?.partyId||""} required searchPlaceholder="Search customers…"><option value="">Select customer</option>{state.parties.filter(p=>["Customer","Both"].includes(p.type)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</SearchableSelect></Field><Field label="Pending date"><input name="pendingDate" type="date" defaultValue={order?.pendingDate||dateNow()} required/></Field><Field label="Required / promised date"><input name="requiredDate" type="date" defaultValue={order?.requiredDate||""}/></Field><Field label="Notes"><input name="notes" defaultValue={order?.notes||""}/></Field></div><div className="line-editor"><div className="order-line order-head"><span>Item</span><span>Required quantity</span><span>Price per piece</span><span>Total</span><span/></div>{lines.map((l,i)=><div className="order-line" key={i}><SearchableSelect value={l.itemId} onChange={e=>update(i,"itemId",e.target.value)} required searchPlaceholder="Search products…"><option value="">Select product</option>{state.items.filter(x=>x.type==="Finished Good").map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</SearchableSelect><input type="number" min="0.01" step="0.01" value={l.quantity} onChange={e=>update(i,"quantity",e.target.value)} required/><input type="number" min="0" step="0.01" value={l.rate} onChange={e=>update(i,"rate",e.target.value)} required/><b>{money(Number(l.quantity)*Number(l.rate))}</b><button type="button" onClick={()=>lines.length>1&&setLines(lines.filter((_,n)=>n!==i))}>×</button></div>)}<button className="add-row" type="button" onClick={()=>setLines([...lines,{itemId:"",quantity:1,rate:0}])}>+ Add product line</button></div><ErrorText>{error}</ErrorText><FormActions close={close} submit={order?"Save order changes":"Save pending order"}/></form></Modal>;
}

export function BOMForm({ close, bom = null }) {
  const { state, mutate } = useERP();
  const raw = state.items.filter(i => ["Raw Material", "Consumable"].includes(i.type));
  const products = state.items.filter(i => i.type === "Finished Good");
  const [lines, setLines] = useState(bom?.lines?.map(line => ({ ...line })) || [{ itemId: "", rackId: "", quantity: 1 }]);
  const [costs, setCosts] = useState(bom?.costs?.map(cost => ({ ...cost })) || [{ name: "Labour", amount: 0 }, { name: "Electricity", amount: 0 }, { name: "Machine Cost", amount: 0 }, { name: "Packing", amount: 0 }]);
  const [error, setError] = useState("");
  const updateLine = (index, key, value) => setLines(lines.map((x, i) => i === index ? { ...x, [key]: value } : x));
  const updateCost = (index, key, value) => setCosts(costs.map((x, i) => i === index ? { ...x, [key]: value } : x));
  const submit = (e) => { e.preventDefault(); try { const f = Object.fromEntries(new FormData(e.currentTarget)); if (!lines.length || lines.some(l => !l.itemId || Number(l.quantity) <= 0)) throw new Error("Every BOM material line needs an item and quantity."); mutate(s => bom ? updateBOM(s, bom.id, { ...f, lines, costs: costs.filter(c => c.name && Number(c.amount) >= 0) }) : addBOM(s, { ...f, lines, costs: costs.filter(c => c.name && Number(c.amount) >= 0) }), "bom"); close(); } catch (err) { setError(err.message); } };
  return <Modal title={bom ? `Edit ${bom.name}` : "Create Bill of Materials"} eyebrow="PRODUCT RECIPE & COSTING" close={close} wide><form onSubmit={submit}><div className="form-grid three"><Field label="BOM name"><input name="name" defaultValue={bom?.name || ""} placeholder="Tractor Hub Standard" required /></Field><Field label="Finished product"><SearchableSelect name="productId" defaultValue={bom?.productId || ""} required><option value="">Select product</option>{products.map(p => <option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</SearchableSelect></Field><Field label="BOM version"><input name="version" defaultValue={bom?.version || "1.0"} /></Field><Field label="Standard output quantity"><input name="outputQty" type="number" min="0.01" step="0.01" defaultValue={bom?.outputQty || 1} required /></Field><Field label="Notes"><input name="notes" defaultValue={bom?.notes || ""} /></Field></div><div className="section-label"><span>Raw materials for the standard output</span><button type="button" onClick={() => setLines([...lines, { itemId: "", rackId: "", quantity: 1 }])}>+ Material</button></div>{lines.map((line, i) => <div className="bom-row" key={i}><SearchableSelect value={line.itemId} onChange={e => updateLine(i, "itemId", e.target.value)} required><option value="">Select raw material</option>{raw.map(x => <option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</SearchableSelect><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e => updateLine(i, "quantity", e.target.value)} /><SearchableSelect value={line.rackId} onChange={e => updateLine(i, "rackId", e.target.value)}><option value="">Preferred issue rack</option>{state.racks.map(r => <option value={r.id} key={r.id}>{r.code}</option>)}</SearchableSelect><button type="button" onClick={() => lines.length > 1 && setLines(lines.filter((_, n) => n !== i))}>×</button></div>)}<div className="section-label"><span>Conversion costs for the standard output</span><button type="button" onClick={() => setCosts([...costs, { name: "", amount: 0 }])}>+ Custom cost</button></div>{costs.map((cost, i) => <div className="cost-row" key={i}><input value={cost.name} onChange={e => updateCost(i, "name", e.target.value)} placeholder="Cost name" /><input type="number" min="0" step="0.01" value={cost.amount} onChange={e => updateCost(i, "amount", e.target.value)} /><span>per standard output</span><button type="button" onClick={() => setCosts(costs.filter((_, n) => n !== i))}>×</button></div>)}<ErrorText>{error}</ErrorText><FormActions close={close} submit={bom ? "Save BOM changes" : "Save BOM"} /></form></Modal>;
}

export function ProductionForm({ close }) {
  const { state, mutate } = useERP();
  const [bomId, setBomId] = useState(""), [quantity, setQuantity] = useState(1), [issueRacks, setIssueRacks] = useState({}), [error, setError] = useState("");
  const bom = state.boms.find(b => b.id === bomId);
  const estimate = useMemo(() => { if (!bom) return null; const multiplier = Number(quantity) / Number(bom.outputQty); const materials = bom.lines.map(line => { const item = state.items.find(i => i.id === line.itemId); const required = Number(line.quantity) * multiplier; return { ...line, item, required, cost: required * Number(item?.cost || 0) }; }); const materialCost = materials.reduce((s, x) => s + x.cost, 0); const conversion = bom.costs.reduce((s, x) => s + Number(x.amount) * multiplier, 0); return { materials, materialCost, conversion, total: materialCost + conversion }; }, [bom, quantity, state.items]);
  const submit = (e) => { e.preventDefault(); try { const f = Object.fromEntries(new FormData(e.currentTarget)); mutate(s => postProduction(s, { ...f, bomId, quantity, issueRacks }), "production"); close(); } catch (err) { setError(err.message); } };
  return <Modal title="Post production order" eyebrow="BOM CONSUMPTION + FINISHED OUTPUT" close={close} wide><form onSubmit={submit}>
    <div className="form-grid three">
      <Field label="BOM / recipe"><SearchableSelect value={bomId} onChange={e => { setBomId(e.target.value); const selected = state.boms.find(b => b.id === e.target.value); setQuantity(selected?.outputQty || 1); }} required searchPlaceholder="Search BOMs…"><option value="">Select BOM</option>{state.boms.filter(b => b.active).map(b => <option key={b.id} value={b.id}>{b.name} · v{b.version}</option>)}</SearchableSelect></Field>
      <Field label="Production date"><input name="date" type="date" defaultValue={dateNow()} required /></Field>
      <Field label="Quantity to produce"><input value={quantity} onChange={e => setQuantity(e.target.value)} type="number" min="0.01" step="0.01" required /></Field>
      <Field label="Finished goods rack (optional)"><SearchableSelect name="outputRackId" searchPlaceholder="Search racks…"><option value="">No rack / unassigned</option>{state.racks.map(r => <option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</SearchableSelect></Field>
      <Field label="Additional batch cost"><input name="additionalCost" type="number" min="0" step="0.01" defaultValue="0" /></Field>
      <Field label="Batch note"><input name="note" /></Field>
    </div>
    {estimate && <>
      <div className="section-label"><span>Automatic material issue</span><b>{bom.productId && state.items.find(i => i.id === bom.productId)?.name}</b></div>
      <div className="material-preview">{estimate.materials.map(line => {
        const selectedRack = issueRacks[line.itemId] || line.rackId || "";
        return <div key={line.itemId}><div><strong>{line.item?.name}</strong><small>Required: {line.required} {line.item?.unit} · Available: {stockFor(state, line.itemId, selectedRack || null)} · {money(line.cost)}</small></div><SearchableSelect value={selectedRack} onChange={e => setIssueRacks({ ...issueRacks, [line.itemId]: e.target.value })} searchPlaceholder="Search issue racks…"><option value="">No rack / use overall stock</option>{state.racks.map(r => <option value={r.id} key={r.id}>{r.code}</option>)}</SearchableSelect></div>;
      })}</div>
      <div className="cost-summary"><div><span>Raw material</span><b>{money(estimate.materialCost)}</b></div>{bom.costs.map(c => <div key={c.name}><span>{c.name}</span><b>{money(Number(c.amount) * Number(quantity) / Number(bom.outputQty))}</b></div>)}<div className="grand"><span>Estimated total / unit</span><b>{money(estimate.total)} / {money(estimate.total / Number(quantity))}</b></div></div>
    </>}
    <ErrorText>{error}</ErrorText><FormActions close={close} submit="Post production" />
  </form></Modal>;
}

export function PaymentForm({ close, payment = null }) {
  const { state, mutate } = useERP();
  const [direction, setDirection] = useState(payment?.direction || "Receipt"), [paymentMethod, setPaymentMethod] = useState(payment?.paymentMethod || "Cheque"), [error, setError] = useState("");
  useEffect(() => {
    if (payment) return undefined;
    const chooseDirection = event => {
      const button = event.target.closest(".segmented button");
      if (!button) return;
      setDirection(button.textContent.includes("Vendor") ? "Payment" : "Receipt");
    };
    document.addEventListener("click", chooseDirection);
    return () => document.removeEventListener("click", chooseDirection);
  }, [payment]);
  const submit = (e) => { e.preventDefault(); try { const values = { ...Object.fromEntries(new FormData(e.currentTarget)), direction }; mutate(s => payment ? updatePayment(s, payment.id, values) : postPayment(s, values), "accounts"); close(); } catch (err) { setError(err.message); } };
  return <Modal title={payment ? `Edit ${payment.document}` : "Record party payment"} eyebrow="CUSTOMER RECEIPT / VENDOR PAYMENT" close={close}><form onSubmit={submit}><div className="segmented"><button type="button" className={direction === "Receipt" ? "active" : ""} disabled={!!payment}>Customer receipt</button><button type="button" className={direction === "Payment" ? "active" : ""} disabled={!!payment}>Vendor payment</button></div><div className="form-grid two"><Field label="Party"><SearchableSelect name="partyId" defaultValue={payment?.partyId || ""} required><option value="">Select party</option>{state.parties.filter(p => direction === "Receipt" ? ["Customer", "Both"].includes(p.type) : ["Supplier", "Both"].includes(p.type)).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</SearchableSelect></Field><Field label="Posting date"><input name="date" type="date" defaultValue={payment?.date || dateNow()} required /></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" defaultValue={payment?.amount || ""} required /></Field><Field label="Payment type"><SearchableSelect name="paymentMethod" value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)} required><option>Cheque</option><option>Bank transfer</option><option>Cash</option><option>Online payment</option><option>Other</option></SearchableSelect></Field><Field label="Cash / bank account"><SearchableSelect name="accountId" defaultValue={payment?.accountId || ""} required><option value="">Select account</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></Field>{paymentMethod === "Cheque" && <><Field label="Cheque date"><input name="chequeDate" type="date" defaultValue={payment?.chequeDate || dateNow()} required /></Field><Field label="Cheque number"><input name="chequeNumber" defaultValue={payment?.chequeNumber || ""} required /></Field></>}<Field label="Reference"><input name="reference" defaultValue={payment?.reference || ""} /></Field><Field label="Description"><input name="description" defaultValue={payment?.description || ""} /></Field></div>{payment && <p className="form-note">Saving reverses the previous ledger and journal posting, then reposts the corrected payment under the same document number.</p>}<ErrorText>{error}</ErrorText><FormActions close={close} submit={payment ? "Save payment changes" : `Post ${direction.toLowerCase()}`} /></form></Modal>;
}

export function BankTransferForm({ close }) {
  const { state, mutate } = useERP();
  const [error, setError] = useState("");
  const submit = event => { event.preventDefault(); try { mutate(current => postBankTransfer(current, Object.fromEntries(new FormData(event.currentTarget))), "accounts"); close(); } catch (reason) { setError(reason.message); } };
  return <Modal title="Intra bank transfer" eyebrow="ACCOUNT TO ACCOUNT MOVEMENT" close={close}><form onSubmit={submit}><div className="form-grid two"><Field label="Transfer date"><input name="date" type="date" defaultValue={dateNow()} required /></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" required /></Field><Field label="From account"><SearchableSelect name="fromAccountId" required><option value="">Select source account</option>{state.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</SearchableSelect></Field><Field label="To account"><SearchableSelect name="toAccountId" required><option value="">Select destination account</option>{state.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</SearchableSelect></Field><Field label="Reference"><input name="reference" /></Field><Field label="Note"><input name="note" /></Field></div><p className="form-note">The destination account is debited and the source account is credited in one balanced journal entry.</p><ErrorText>{error}</ErrorText><FormActions close={close} submit="Post transfer" /></form></Modal>;
}

export function ExpenseForm({ close }) {
  const { state, mutate } = useERP(); const [error, setError] = useState("");
  const submit = e => { e.preventDefault(); try { mutate(s => postExpense(s, Object.fromEntries(new FormData(e.currentTarget))), "expenses"); close(); } catch (err) { setError(err.message); } };
  return <Modal title="Record expense" eyebrow="OPERATING / FACTORY COST" close={close}><form onSubmit={submit}><div className="form-grid two"><Field label="Date"><input name="date" type="date" defaultValue={dateNow()} required /></Field><Field label="Category"><SearchableSelect name="category" required searchPlaceholder="Search expense categories…"><option value="">Select category</option><option>Salary</option><option>Electricity</option><option>Fuel</option><option>Transport</option><option>Office</option><option>Factory</option><option>Other</option></SearchableSelect></Field><Field label="Description"><input name="description" required /></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" required /></Field><Field label="Paid from"><SearchableSelect name="accountId" required searchPlaceholder="Search cash and bank accounts…"><option value="">Select account</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></Field><Field label="Payee"><input name="payee" /></Field></div><ErrorText>{error}</ErrorText><FormActions close={close} submit="Post expense" /></form></Modal>;
}

export function UserForm({ close }) {
  const { state, mutate } = useERP(); const [error, setError] = useState(""); const [role, setRole] = useState("Viewer");
  const permissions = [...new Set(Object.values(state.settings.roles).flat().filter(p => p !== "all"))];
  const submit = async e => { e.preventDefault(); setError(""); const form = new FormData(e.currentTarget); try { const response = await fetch("/api/users", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ name:form.get("name"), username:form.get("username"), password:form.get("password"), department:form.get("department"), role, permissions: role === "Administrator" ? ["all"] : form.getAll("permissions") }) }); const data=await response.json(); if(!response.ok) throw new Error(data.error); mutate(s=>recordAudit(s,`Created system user ${form.get("username")}`,`${form.get("name")} · ${role}`),"all"); window.dispatchEvent(new Event("users-updated")); close(); } catch(err){setError(err.message)} };
  return <Modal title="Add system user" eyebrow="USER PERMISSIONS" close={close} wide><form onSubmit={submit}><div className="form-grid two"><Field label="Full name"><input name="name" required /></Field><Field label="Username"><input name="username" required /></Field><Field label="Password (minimum 6 characters)"><input name="password" type="password" minLength="6" required /></Field><Field label="Department"><input name="department" /></Field><Field label="Role"><SearchableSelect value={role} onChange={e=>setRole(e.target.value)} searchPlaceholder="Search roles…">{Object.keys(state.settings.roles).map(r=><option key={r}>{r}</option>)}</SearchableSelect></Field></div>{role!=="Administrator"&&<fieldset key={role} className="permission-grid"><legend>Allowed modules</legend>{permissions.map(p=><label key={p}><input type="checkbox" name="permissions" value={p} defaultChecked={state.settings.roles[role]?.includes(p)}/><span>{p}</span></label>)}</fieldset>}<p className="form-note">Permissions are enforced by the server API, not only hidden in the interface.</p><ErrorText>{error}</ErrorText><FormActions close={close} submit="Create user" /></form></Modal>;
}
